#!/bin/sh
# preinst script for scribes
#
# see: dh_installdeb(1)

set -e

# Remove the Scribes Python library ($PYTHONDIR/SCRIBES). Apt doesn't 
# do this. If there's a better way to do this please let me know.

echo "Removing Scribes Python libray"

echo '#! /usr/bin/env python\n# -*- coding: utf8 -*-\n\ndef remove_lib(scribes_folder_name):\n\timport sys\n\tfrom os.path import join, exists\n\tfrom shutil import rmtree\n\tfor path in sys.path:\n\t\tscribeslib = join(path, "SCRIBES")\n\t\tif scribeslib.startswith("/usr") is False: continue\n\t\tif exists(scribeslib) is False: continue\n\t\tprint "Removing %s" % scribeslib\n\t\trmtree(scribeslib)\n\t\tprint "Removed %s" % scribeslib\n\treturn False\n\ndef removes_libs():\n\tfolder_names = ("SCRIBES", "Scribes", "scribes")\n\t[remove_lib(name) for name in folder_names]\n\treturn False\n\nif __name__ == "__main__":\n\tremoves_libs()\n' > removescribeslibs.py

python removescribeslibs.py

rm -rf removescribeslibs.py

echo "Removed Scribes Python library"

#DEBHELPER#
